version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile  # Use the same Dockerfile
    ports:
      - "4400:4200"  # Expose Angular development server port
    volumes:
      - .:/app  # Mount the current directory for live reloading
    environment:
      - NODE_ENV=development
    command: ng serve --host 0.0.0.0  # Run Angular in development mode with live reload

    # Restart always is typically for production services. For development, you may not need this.
    # restart: always
